name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
      env:
        LOG : ${{ secrets.DOCKER_LOGIN }}
        PWD : ${{ secrets.DOCKER_PWD }}
        NAME : ${{ secrets.DOCKER_NAME }}

      run: |
        echo $LOG
        echo $NAME
        docker build . --file Dockerfile --tag $LOG/$NAME:news_admin
        echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
        docker push $LOG/$NAME:news_admin
