name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  

  build:

    runs-on: ubuntu-latest

    steps:
    - name: set env
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo ${{ secrets.DOCKER_LOGIN }}
        echo ${{ secrets.DOCKER_NAME }}
        export REV=$(date +%s)
        docker build . --file Dockerfile --tag dragsnake/cmasf:news_admin:$REV
      
    - name: Push to Dockerhub
      run: docker push dragsnake/cmasf:news_admin:REV
