name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $LOGIN/$NAME:news_admin
      env:
        LOGIN: ${{ secrets.DOCKER_LOGIN }}
        NAME: ${{ secrets.DOCKER_NAME }}
        PASSW: ${{ secrets.DOCKER_PWD }}
    - name: Push to Dockerhub
      run: docker push $LOGIN/$NAME:news_admin
